// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Pgvector;
using SUPPORT.Infrastructure.Persistence;

#nullable disable

namespace SUPPORT.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SupportDbContext))]
    [Migration("20261008152917_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SUPPORT.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("product");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_chat_conversation");

                    b.HasIndex("Product", "OrgId", "UserId", "LastMessageAt")
                        .IsDescending(false, false, false, true)
                        .HasDatabaseName("ix_chat_conversation_product_org_id_user_id_last_message_at")
                        .HasFilter("is_deleted = false");

                    b.ToTable("chat_conversation", (string)null);
                });

            modelBuilder.Entity("SUPPORT.Domain.Entities.ConversationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Citations")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("citations");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("integer")
                        .HasColumnName("completion_tokens");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsInterrupted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_interrupted");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("PageRoute")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("page_route");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_tokens");

                    b.Property<short>("Role")
                        .HasColumnType("smallint")
                        .HasColumnName("role");

                    b.Property<float?>("TopScore")
                        .HasColumnType("real")
                        .HasColumnName("top_score");

                    b.HasKey("Id")
                        .HasName("pk_chat_message");

                    b.HasIndex("ConversationId", "CreatedAt")
                        .HasDatabaseName("ix_chat_message_conversation_id_created_at");

                    b.ToTable("chat_message", (string)null);
                });

            modelBuilder.Entity("SUPPORT.Domain.Entities.IngestionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChunksWritten")
                        .HasColumnType("integer")
                        .HasColumnName("chunks_written");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DocsArchived")
                        .HasColumnType("integer")
                        .HasColumnName("docs_archived");

                    b.Property<int>("DocsChanged")
                        .HasColumnType("integer")
                        .HasColumnName("docs_changed");

                    b.Property<int>("DocsScanned")
                        .HasColumnType("integer")
                        .HasColumnName("docs_scanned");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("product");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("trigger");

                    b.HasKey("Id")
                        .HasName("pk_kb_ingestion_run");

                    b.HasIndex("Product", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_kb_ingestion_run_product_started_at");

                    b.ToTable("kb_ingestion_run", (string)null);
                });

            modelBuilder.Entity("SUPPORT.Domain.Entities.KnowledgeChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("embedding_model");

                    b.Property<string>("HeadingPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("heading_path");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("module");

                    b.Property<Guid?>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("product");

                    b.Property<NpgsqlTsVector>("SearchTsv")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_tsv")
                        .HasComputedColumnSql("to_tsvector('simple', support_unaccent(heading_path || ' ' || content))", true);

                    b.Property<int>("TokenCount")
                        .HasColumnType("integer")
                        .HasColumnName("token_count");

                    b.HasKey("Id")
                        .HasName("pk_kb_chunk");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_kb_chunk_embedding")
                        .HasAnnotation("Npgsql:StorageParameter:ef_construction", 64)
                        .HasAnnotation("Npgsql:StorageParameter:m", 16);

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("SearchTsv")
                        .HasDatabaseName("ix_kb_chunk_search_tsv");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchTsv"), "gin");

                    b.HasIndex("DocumentId", "ChunkIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_kb_chunk_document_id_chunk_index");

                    b.HasIndex("Product", "OrgId", "Module")
                        .HasDatabaseName("ix_kb_chunk_product_org_id_module");

                    b.ToTable("kb_chunk", (string)null);
                });

            modelBuilder.Entity("SUPPORT.Domain.Entities.KnowledgeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("module");

                    b.Property<Guid?>("OrgId")
                        .HasColumnType("uuid")
                        .HasColumnName("org_id");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("product");

                    b.Property<string>("RouteHint")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("route_hint");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("source_key");

                    b.Property<short>("SourceType")
                        .HasColumnType("smallint")
                        .HasColumnName("source_type");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.PrimitiveCollection<List<string>>("Suggestions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("suggestions");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_kb_document");

                    b.HasIndex("Product", "OrgId", "SourceKey")
                        .IsUnique()
                        .HasDatabaseName("ix_kb_document_product_org_id_source_key");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("Product", "OrgId", "SourceKey"), false);

                    b.ToTable("kb_document", (string)null);
                });

            modelBuilder.Entity("SUPPORT.Domain.Entities.MessageFeedback", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<short>("Rating")
                        .HasColumnType("smallint")
                        .HasColumnName("rating");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("MessageId")
                        .HasName("pk_chat_feedback");

                    b.ToTable("chat_feedback", null, t =>
                        {
                            t.HasCheckConstraint("ck_chat_feedback_rating", "rating IN (-1, 1)");
                        });
                });

            modelBuilder.Entity("SUPPORT.Domain.Entities.ConversationMessage", b =>
                {
                    b.HasOne("SUPPORT.Domain.Entities.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_message_chat_conversation_conversation_id");
                });

            modelBuilder.Entity("SUPPORT.Domain.Entities.KnowledgeChunk", b =>
                {
                    b.HasOne("SUPPORT.Domain.Entities.KnowledgeDocument", null)
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kb_chunk_kb_document_document_id");
                });

            modelBuilder.Entity("SUPPORT.Domain.Entities.MessageFeedback", b =>
                {
                    b.HasOne("SUPPORT.Domain.Entities.ConversationMessage", null)
                        .WithOne()
                        .HasForeignKey("SUPPORT.Domain.Entities.MessageFeedback", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_feedback_chat_message_message_id");
                });

            modelBuilder.Entity("SUPPORT.Domain.Entities.KnowledgeDocument", b =>
                {
                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
